### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Kugelschieber** [andreashauschild/openttd-server#2]
Hey, I just wanted to thank you for building this. It's fantastic having a web UI to manage the servers. I set up the docker image, added a subdomain to Caddy (to get an SSL certificate), and voila, works like a charm!

![grafik](https://user-images.githubusercontent.com/6115423/210859854-04fab2d8-41f4-46aa-921b-8a96d437f710.png)

Just in case you would like to add an example docker-compose, here is mine:

```yaml
version: "3"

volumes:
  data:

services:
  openttd:
    image: hauschi86/openttd-server:v12.2.1
    container_name: openttd
    restart: unless-stopped
    ports:
      - "8294:8080"
      - "3979-3999:3979-3999"
    volumes:
      - data:/home/openttd/server
```

And these are the lines I've added to `/etc/caddy/Caddyfile`:

```
openttd.your-domain.com:443 {
	reverse_proxy localhost:8294
}
```

I've changed the port from 8080 to 8294.
