### ISSUE TITLE
Docker compose - persistent storage

### ISSUE THREAD

**Issue by tjerkkamstra** [andreashauschild/openttd-server#5]
Hi,

I really apreciate the work you done here. I created another compose file, now with local storage binding. It makes it easier to have a look into the config files for me. Make sure your docker user has sufficient rights to access and write it though!

```
version: "2.1"
services:
  openttd-server:
    image: hauschi86/openttd-server:latest
    container_name: openttd-server
    volumes:
      - /path/to/local/drive/openttd-server:/home/openttd/server
    ports:
      - 8087:8080
	  - 3979-3999:3979-3999/tcp
	  - 3979-3999:3979-3999/udp
    restart: unless-stopped
```
